name: qiskit-metal
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - addict
  - descartes
  - gdspy>=1.5.2
  - geopandas
  - ipython
  - matplotlib
  #Due to issue with qutip, limit the version of numpy. Wait for pull request to merge. https://github.com/qutip/qutip/pull/1752
  - numpy<1.22
  - pandas
  - pint
  - pyepr-quantum>=0.8.4.6
  - pygments
  - pyside2
  - qutip
  - scipy
  - shapely
  - jupyter
  - scqubits
